#https://qiita.com/murakami-mm/items/9587e21fc0ed57c803d0
#
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_api:
    docker:
      - image: circleci/ruby:3.0.2
    working_directory: ~/myapp/api
    steps:
      - checkout:
          path: ~/myapp
      - ruby/install-deps
      
  test_api:
    docker:
      - image: circleci/ruby:3.0.2
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp-test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/myapp/api
    steps:
      - checkout:
          path: ~/myapp
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test
    
  deploy:
    docker:
      - image: circleci/ruby:3.0.2
    working_directory: ~/myapp/api
    steps:
      - checkout:
          path: ~/myapp
      - setup_remote_docker:
          version: 20.10.6
      - heroku/install
      - run:
          name: heroku login -i
          command: heroku container:login
      - run:
          name: 実験
          command: ls
      - run:
          name: push docker image
          command: heroku container:push api -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release api -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_api
      - test_api:
          requires:
            - build_api
      #- deploy:
      #    requires:
      #      - test
      #    filters:
      #      branches:
      #        only: master