default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>
  timeout: 5000

development:
  <<: *default
  database: myapp-development

test:
  <<: *default
  database: myapp-test

production:
  <<: *default
  database: myapp-production
